/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const NewsId = IDL.Nat;
export const ContactMessageId = IDL.Nat;
export const ContactMessage = IDL.Record({
  'id' : ContactMessageId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const MemberId = IDL.Nat;
export const MemberRole = IDL.Variant({
  'policy_maker' : IDL.Null,
  'entrepreneur' : IDL.Null,
  'other' : IDL.Null,
  'civil_society' : IDL.Null,
  'youth' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : MemberId,
  'name' : IDL.Text,
  'role' : MemberRole,
  'email' : IDL.Text,
  'state' : IDL.Text,
  'message' : IDL.Text,
  'organization' : IDL.Text,
});
export const NewsItem = IDL.Record({
  'id' : NewsId,
  'title' : IDL.Text,
  'date' : Time,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'organization' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNewsItem' : IDL.Func(
      [IDL.Text, Time, IDL.Text, IDL.Text],
      [NewsId],
      [],
    ),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getAllNewsItems' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getForumStatistics' : IDL.Func(
      [],
      [
        IDL.Record({
          'other' : IDL.Nat,
          'entrepreneurs' : IDL.Nat,
          'civilSociety' : IDL.Nat,
          'totalMembers' : IDL.Nat,
          'youth' : IDL.Nat,
          'policyMakers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerMember' : IDL.Func(
      [IDL.Text, IDL.Text, MemberRole, IDL.Text, IDL.Text, IDL.Text],
      [MemberId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactMessageId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const NewsId = IDL.Nat;
  const ContactMessageId = IDL.Nat;
  const ContactMessage = IDL.Record({
    'id' : ContactMessageId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const MemberId = IDL.Nat;
  const MemberRole = IDL.Variant({
    'policy_maker' : IDL.Null,
    'entrepreneur' : IDL.Null,
    'other' : IDL.Null,
    'civil_society' : IDL.Null,
    'youth' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : MemberId,
    'name' : IDL.Text,
    'role' : MemberRole,
    'email' : IDL.Text,
    'state' : IDL.Text,
    'message' : IDL.Text,
    'organization' : IDL.Text,
  });
  const NewsItem = IDL.Record({
    'id' : NewsId,
    'title' : IDL.Text,
    'date' : Time,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'organization' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNewsItem' : IDL.Func(
        [IDL.Text, Time, IDL.Text, IDL.Text],
        [NewsId],
        [],
      ),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getAllNewsItems' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getForumStatistics' : IDL.Func(
        [],
        [
          IDL.Record({
            'other' : IDL.Nat,
            'entrepreneurs' : IDL.Nat,
            'civilSociety' : IDL.Nat,
            'totalMembers' : IDL.Nat,
            'youth' : IDL.Nat,
            'policyMakers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerMember' : IDL.Func(
        [IDL.Text, IDL.Text, MemberRole, IDL.Text, IDL.Text, IDL.Text],
        [MemberId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactMessageId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };