/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : ContactMessageId,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export type ContactMessageId = bigint;
export interface Member {
  'id' : MemberId,
  'name' : string,
  'role' : MemberRole,
  'email' : string,
  'state' : string,
  'message' : string,
  'organization' : string,
}
export type MemberId = bigint;
export type MemberRole = { 'policy_maker' : null } |
  { 'entrepreneur' : null } |
  { 'other' : null } |
  { 'civil_society' : null } |
  { 'youth' : null };
export type NewsId = bigint;
export interface NewsItem {
  'id' : NewsId,
  'title' : string,
  'date' : Time,
  'summary' : string,
  'category' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'organization' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNewsItem' : ActorMethod<[string, Time, string, string], NewsId>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getAllNewsItems' : ActorMethod<[], Array<NewsItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getForumStatistics' : ActorMethod<
    [],
    {
      'other' : bigint,
      'entrepreneurs' : bigint,
      'civilSociety' : bigint,
      'totalMembers' : bigint,
      'youth' : bigint,
      'policyMakers' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerMember' : ActorMethod<
    [string, string, MemberRole, string, string, string],
    MemberId
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    ContactMessageId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];